### ISSUE TITLE
Lan Port is unstable

### ISSUE THREAD

**Issue by sintian** [TechNexion-customization/ubuntu-tn-imx#8] opened 2021-09-24 06:41 UTC
Hello,
I refer to "IMX6/IMX7 Platforms for Ubuntu 20.04 with X11 Framework", and follow the steps, but found that the Lan Port is very unstable, using WinSCP or PuTTy connection is easy to disconnect, but the original use of other versions are very stable, how to solve the problem?
Thanks!

**Comment by wigcheng** [comment] 2021-09-24 07:30
What's your platform? and do you have a specific version for 'original use of other versions'?

Thanks

**Comment by sintian** [comment] 2021-09-24 09:19
Thanks for your quick reply!

My platform is i.MX6, and I used ubuntu 16.04 before. Could you please tell me which direction to deal with it?

In addition, I have another question about the screen boundary. On the 7-inch monitor of i.mx6 (resolution 800x480), there is always a situation where the screen exceeds the target panel. I have followed the modification suggestions (line 103 of gen_image.sh)), is there any way to fix the problem?
Thanks

**Comment by wigcheng** [comment] 2021-09-27 02:40
Which IMX6 board do you use, PICO-IMX6 or EDM-IMX6? Provide specific board set information can speed up reproduce issue here, thanks!

About 7" monitor, did you modify timing setting on dts? Or create a new dtb and put it in partition 1? And This monitor should be VGA interface, right? You need make sure your system load right dtb first, if still have screen boundary issue, could be need tune the timing such as VFP, HFP parameter manually in dts.

**Comment by sintian** [comment] 2021-09-27 08:40
Hi, @wigcheng :
1. I use PICOIMX6U10R10E169377 with BLE wifi, Base Board: PICONYMPHGL.
Please give me advice on how to deal with Lan Port's instability.

2. I have modified imx6qdl-pico.dtsi (location: output/kernel/linux-tn-imx/arch/arm/boot/dts/), the previous standalone modification is feasible, but it is not feasible this time.
Such as
&ldb {
	clock-frequency = <29500000>;
	hactive = <800>;
	vactive = <480>;
}
And the monitor is LVDS interface. I will pay more attention to VFP and HFP parameters.
thank you!

**Comment by wigcheng** [comment] 2021-09-28 03:20
About Ethernet issue.
I cannot reproduce here: my set is PICO-IMX6 Quad-Core with NYMPH baseboard.
Take one notebook with Windows 10 OS, get a DHCP IP from router (same network segment with the board), and open the putty, connect to the board via ssh, and don't do anything over half hour, it still alive.

BUT you mention you works perfectly on earlier Ubuntu OS, so should be not hardware issue, it's configuration issue I think, after all, there are different openssh-server version between 16.04 and 20.04, maybe add new functions. 

I googling and find some possible reason as follows link, you can try it first.
https://askubuntu.com/questions/644869/how-to-stop-ssh-disconnect-after-a-a-certain-amount-of-time
https://rbgeek.wordpress.com/2013/03/16/keep-putty-ssh-sessions-from-disconnecting/

**Comment by sintian** [comment] 2021-09-28 08:31
Hi, @wigcheng :
Thank you for the link, although the problem still exists after trying.

Maybe I didn't make this clear enough. For Ethernet issue, it's easy to break the connection when using puTTy (if using SSH), but not when using Serial. Besides, the main problem of the Ethernet is that the download speed is slow and will fail. For example, I always get an error when I use apt-get update or install (Error message: E: Failed to fetch http://ports.ubuntu.com/ubuntu -ports/dists/focal-security/main/binary-armhf/Packages Connection failed [IP: 91.189.91.39 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.), and it is easy to disconnect when I use WinSCP to transfer files.

I will pay more attention to the configuration problem. 
Any help will be most appreciated.

**Comment by wigcheng** [comment] 2021-09-29 03:05
I need look for a PICO-IMX6DL and test again, need some time, thanks!

**Comment by wigcheng** [comment] 2021-09-29 07:18
Hello, I can reproduce here using PICO-IMX6 Dual-Lite, really so sorry cause your inconvenience, I'm processing to fix this bug, I'll fix you ASAP when I've done.

**Comment by wigcheng** [comment] 2021-09-29 07:46
Hello, could you provide your serial code number on the board? It's on the another side (mPCIE side) of RJ45 connector such as 2024.

Thanks

**Comment by wigcheng** [comment] 2021-09-29 09:11
Do you have the github name and email address, I'll update commit to fix this issue, but I would like add you in the commit something like:

Reported-by: sintian  <sintian@gmail.com>

Could you provide it to me? Thanks a lot

**Comment by sintian** [comment] 2021-09-29 10:14
Hi, @wigcheng  :
Thank you for your prompt help!
Reported-by: sintian peug5213@gmail.com

serial code number: 1836
Just in case I still attach a photo to this URL:
https://www.dropbox.com/s/dhpuc0h0fflzvps/IMG_0960.jpg?dl=0

I have recorded the network disconnection. If you need to refer to it, please refer to this URL: https://www.dropbox.com/s/580uwniodrb78wf/%E5%BD%B1%E7%89%87%202021-9-29% 2014%2022%2050.mov?dl=0

Regarding other unsolved issues:
1. As mentioned above about the screen border, I modified the dtsi file(imx6qdl-pico.dtsi), but where do I want to make dtb and how do I issue the command?
2. There are also wifi problems. Ifconfig wlan0 up is successful, but the device cannot sense wifi, do I need to set something?
I am very grateful for your assistance!

**Comment by wigcheng** [comment] 2021-09-30 02:01
I already push the commit which fix ethernet issue, please try it first, and feedback here if no problems, 
 let's step by step, thanks.

**Comment by sintian** [comment] 2021-09-30 09:13
Hi @wigcheng: 
Thank you so much, now the internet and wifi can be used normally!
In addition, the problem of screen borders has also been found to be solved.

But there is another question about Bluetooth. I clicked to turn on Bluetooth on the desktop but there was no response. I also tried some methods, such as: serial-qcabtfw@* (this service) was not found with the systemd command. Or use the hciconfig command without success (refer to this URL:
https://www.dropbox.com/s/2exi9adtb0k3p07/image_2021_09_30T08_27_07_299Z.png?dl=0).
Do you have any suggestions? And can WIFI and BLE coexist?

Thanks!

**Comment by sintian** [comment] 2021-10-01 06:34
Sorry to correct my email:
fm.rd6@futuremate.com.tw
Hope it didn't cause you trouble.

**Comment by wigcheng** [comment] 2021-10-04 05:52
Corrected your mail but you have to force update repo again:
https://github.com/TechNexion-customization/ubuntu-tn-imx/commit/de57caac7860a10732a628453765dd9dfeb37077

WiFi and Bluetooth can coexist of course, but could you close this ticket first and create another ticket to discuss Bluetooth question, I hope keep the ticket more clean, it's easy to lookup record for other users in the future.

**Comment by sintian** [comment] 2021-10-04 06:24
Ok, I get it, thanks for your reply!
I will create another ticket about Bluetooth question.
Best regards.

**Closed as completed** 2021-10-04 06:42 UTC
