### ISSUE TITLE
Bluetooth connection issue

### ISSUE THREAD

**Issue by sintian** [TechNexion-customization/ubuntu-tn-imx#10] opened 2021-10-04 06:39 UTC
I refer to "IMX6/IMX7 Platforms for Ubuntu 20.04 with X11 Framework" and follow the steps. Finally, I clicked to turn on Bluetooth in the .mx6 panel, but nothing happened. I also tried some methods in putty, for example: I can't find serial-qcabtfw@* (this service) with the systemd command. Or use the hciconfig command without success (refer to this URL:
https://www.dropbox.com/s/2exi9adtb0k3p07/image_2021_09_30T08_27_07_299Z.png?dl=0).
I used PICOIMX6U10R10E169377 with BLE wifi, substrate: PICONYMPHGL.
Do you have any suggestions,please?

**Comment by wigcheng** [comment] 2021-10-04 06:49
Does your Ubuntu is compiled by yourself? Or use our demo image from ftp server?

Basically, you should see the bluetooth icon on desktop as follows:
https://github.com/TechNexion-customization/ubuntu-tn-imx/blob/master/README-imx6.md#control-bluetooth-connection

If you cannot see it, please make sure you already put bluetooth firmware files in rootfs /lib/firmware folder, I think should be have because your wifi works, right?

Thanks

**Comment by sintian** [comment] 2021-10-04 08:23
hi @wigcheng 
That Ubuntu uses your demo demo image from ftp server.
yes I see the Bluetooth icon on the desktop, but once I click "Turn Bluetooth on
"After the icon disappears, or after clicking, the small icon still shows "Turn Bluetooth on". And the Bluetooth firmware file is also placed there(/lib/firmware folder). I can't imagine what went wrong.
Thanks.

**Comment by wigcheng** [comment] 2021-10-05 03:30
I'll try to reproduce here today, thanks.

**Comment by wigcheng** [comment] 2021-10-05 06:24
Hello @sintian 

I have two questions: 

1. Is your flashed image as follows link?
https://download.technexion.com/demo_software/PICO/IMX6/pico-imx6-emmc/DiskImage/pico-imx6_nymph_ubuntu-20.04-xfce_QCA9377_hdmi-1280x720_20210122.zip

2. Did you trying to compile image by yourself? Because I was improve bluetooth in April as follows log:
https://github.com/TechNexion-customization/ubuntu-tn-imx/commit/4da07cd25b32505ceaf516bd0100cd1d54e640b2

FTP image should be no include this commit, you have to compile it manually.

**Comment by wigcheng** [comment] 2021-10-05 09:57
Hello, I can reproduce your issue here using latest commit, and I fix it already as follows commit:
https://github.com/TechNexion-customization/ubuntu-tn-imx/commit/2ac18316b0409f18dafe3624df97565321d59b59

But not only update repo, I also update rootfs_overlay proprietary tarball file, so I recommend your steps can be:
1. git pull latest commit
2. clean build using make clean first
3. delete rootfs_overlay output folder
4. make image again

Should be works, please try it first and let me know your progress, thanks, really appreciate for your reporting.

Wig

**Comment by sintian** [comment] 2021-10-06 08:29
Hi @wigcheng :
After running according to your suggestion, Bluetooth starts to work!
I sincerely appreciate your help.
Best regards!

**Comment by wigcheng** [comment] 2021-10-06 09:49
Good news! Thanks for your feed back, I close this ticket.

**Closed as completed by wigcheng** 2021-10-06 09:49 UTC
