### ISSUE TITLE
BLE / BD address is 00:00:00:00:00:00 problem

### ISSUE THREAD

**Issue by sintian** [TechNexion-customization/ubuntu-tn-imx#11] opened 2021-10-08 09:12 UTC
Sorry, Bluetooth was used successfully before, but I don’t understand what is wrong now, i.mx6 has not been able to detect the Bluetooth device (same as before, refer to: https://github.com/ TechNexion-customization/ubuntu-tn-imx/issues/10). I have confirmed the firmware files and the modification in qemu_install-imx6_7.sh. Besides, the wifi function is normal. Is there any way to detect the problem?
root@technexion:~# hciconfig -a
hci0: Type: Primary Bus: UART
         BD Address: 00:00:00:00:00:00 ACL MTU: 0:0 SCO MTU: 0:0
         DOWN
         RX bytes:1 acl:0 sco:0 events:0 errors:0
         TX bytes:8 acl:0 sco:0 commands:2 errors:0
         Features: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
         Packet type: DM1 DH1 HV1
         Link policy:
         Link mode: SLAVE ACCEPT

root@technexion:~# hcitool dev
Devices:

root@technexion:~# demesg | grep tooth
[21.748730] Bluetooth: hci0: Frame reassembly failed (-84)

Any help will be most appreciated.

**Comment by wigcheng** [comment] 2021-10-12 02:31
Did you tried re-flash image again and it still doesn't works? Because you said "Bluetooth was used successfully before, but I don’t understand what is wrong now", you don't provide specific reproduce steps, I can't not give you comments, if you works after re-flash image, I think you should be enable or disable something cause bluetooth applications conflicting.

Thanks

**Comment by sintian** [comment] 2021-10-12 07:46
HI @wigcheng :
Yes,I used the SD card to refresh the image, and then put the firmware file into it. I used to successfully use Bluetooth like this before, but now it fails.

Thanks!

**Comment by wigcheng** [comment] 2021-10-12 10:34
Yes, I know your point, so my question is what did you do after flashed and the status is bluetooth works perfectly? Install something or enable/disable some configuration, or it just random failed, or it works back after reboot several times?

If you cannot provide further information, I have no direction to give you comments.

**Comment by sintian** [comment] 2021-10-13 09:31
Sorry for not being clear enough, the steps I did after flashing are as follows:
$sudo apt-get install zip
$sudo apt-get install -y connman
(Winscp put qca9377-3_qca6174-3_firmware_20191128.zip to /home/ubuntu)
$mv /home/ubuntu/qca9377-3_qca6174-3_firmware_20191128.zip /lib/firmware/qca9377-3_qca6174-3_firmware_20191128.zip
$ Unzip qca9377-3_qca6174-3_firmware_20191128.zip

At present, it was only successful when following [2ac1831](https://github.com/TechNexion-customization/ubuntu-tn-imx/commit/2ac18316b0409f18dafe3624df97565321d59b59) for the first time. At that time, it was possible to use Bluetooth directly on the panel without changing the configuration.Later, even after the refresh, just following the above steps failed.
thanks.

**Comment by sintian** [comment] 2021-10-18 03:08
HI @wigcheng 
Is there any more information I need to provide?
Any help will be most appreciated.

**Comment by wigcheng** [comment] 2021-10-18 05:13
So the issue happened after install connman, did you try the issue exists without connman?
Actually connman and network-manager are same function as common sense, so they cannot exist at the same time, they will conflicted, but I'm not sure why it impact bluetooth behavior.

If you want use other application to control wireless functions, please remove network-manager and blueman first to avoid race condition.

Thanks

**Comment by sintian** [comment] 2021-10-18 06:25
Ok, I will try it and report the situation later. Thanks for your reply!

**Comment by sintian** [comment] 2021-10-19 04:02
HI @wigcheng 
I didn't expect the two to be in conflict, that's the problem! Bluetooth function is already normal, thank you very much!

**Comment by wigcheng** [comment] 2021-10-19 05:14
Congrats! I close this ticket, thanks for your feedback.

**Closed as completed by wigcheng** 2021-10-19 05:14 UTC
